#!/usr/bin/env bash

exit_on_error() {
	exit_code=$1
	last_command=${@:2}
	if [ $exit_code -ne 0 ]; then
		>&2 echo "\"${last_command}\" command failed with exit code ${exit_code}."
		exit $exit_code
	fi
}

hugo_root="$(dirname "$0")"

cd "$hugo_root"; exit_on_error $? 'cd $hugo_root'

git pull --commit --no-edit >/dev/null; exit_on_error $? 'git pull'
git add . >/dev/null; exit_on_error $? 'git add'
git commit --all --message "./push: new content" >/dev/null; exit_on_error $? 'git commit'
git push origin main >/dev/null >/dev/null; exit_on_error $? 'git push'

echo "New content pushed to GitHub!"
